# Generated by Django 6.0.4 on 2026-04-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRuleModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('min_members', models.IntegerField()),
                ('max_members', models.IntegerField()),
                ('min_teams', models.IntegerField()),
                ('max_teams', models.IntegerField()),
                ('access_type', models.CharField(max_length=20)),
                ('validation_list', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'competencia_tournament_rule',
            },
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('state', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('creator_user_id', models.CharField(max_length=36)),
                ('tournament_rule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tournament', to='competencia.tournamentrulemodel')),
            ],
            options={
                'db_table': 'competencia_tournament',
            },
        ),
    ]
