# Generated by Django 6.0.4 on 2026-04-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMemberModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('tournament_id', models.CharField(max_length=36)),
                ('rol', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'competencia_tournament_member',
            },
        ),
        migrations.CreateModel(
            name='CriteriaModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('tournament_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='competencia.tournamentrulemodel')),
            ],
            options={
                'db_table': 'competencia_criteria',
            },
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='tournament_members',
            field=models.ManyToManyField(related_name='tournament', to='competencia.tournamentmembermodel'),
        ),
    ]
