# Generated by Django 5.2.13 on 2026-04-29 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0002_tournamentmembermodel_criteriamodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPAnalysisModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_texto', models.TextField()),
                ('numero_equipos', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_tecnico', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_torneo_sugerido', models.CharField(blank=True, max_length=20, null=True)),
                ('intencion_usuario', models.TextField(blank=True, default='')),
                ('nivel_confianza', models.JSONField(default=dict)),
                ('estado_analisis', models.CharField(max_length=20)),
                ('campos_faltantes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competencia_nlp_analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
