# Generated by Django 6.0.4 on 2026-04-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0002_tournamentmembermodel_criteriamodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriamodel',
            name='tournament_rule',
        ),
    ]
