# Generated by Django 5.2.13 on 2026-04-29 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0003_nlpanalysismodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioIAModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('torneo_id', models.CharField(max_length=36)),
                ('sesion_ia_id', models.CharField(db_index=True, max_length=36)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_dato', models.CharField(max_length=10)),
                ('peso_porcentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mayor_es_mejor', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.CharField(default='SUGERIDO', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'competencia_criterio_ia',
                'ordering': ['sesion_ia_id', 'orden'],
            },
        ),
    ]
