# Generated by Django 6.0.4 on 2026-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0003_remove_criteriamodel_tournament_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentrulemodel',
            name='date_end_inscription',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentrulemodel',
            name='date_start_inscription',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
