# Generated by Django 6.0.4 on 2026-04-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0004_tournamentrulemodel_date_end_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriamodel',
            name='max_value_qualification',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='criteriamodel',
            name='min_value_qualification',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='criteriamodel',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='competencia.tournamentmodel'),
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='config_tournament',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
