# Generated by Django 6.0.4 on 2026-04-30 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0005_criteriamodel_max_value_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'competencia_institution',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competencia.tournamentmodel')),
            ],
            options={
                'db_table': 'competencia_group',
            },
        ),
        migrations.CreateModel(
            name='DocenteAsesorModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.institutionmodel')),
            ],
            options={
                'db_table': 'competencia_docente_asesor',
            },
        ),
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ronda', models.IntegerField()),
                ('posicion_en_ronda', models.IntegerField()),
                ('es_bye', models.BooleanField(default=False)),
                ('es_descanso', models.BooleanField(default=False)),
                ('fase', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='PENDING', max_length=50)),
                ('ganador_id', models.CharField(blank=True, max_length=36, null=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competencia.groupmodel')),
                ('partido_siguiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_anteriores', to='competencia.matchmodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competencia.tournamentmodel')),
            ],
            options={
                'db_table': 'competencia_match',
            },
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('nivel_tecnico_declarado', models.CharField(max_length=50)),
                ('estado_inscripcion', models.CharField(max_length=50)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('representante_id', models.CharField(max_length=36)),
                ('docente_asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.docenteasesormodel')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.institutionmodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competencia.tournamentmodel')),
            ],
            options={
                'db_table': 'competencia_team',
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StandingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('puntaje_favor', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('puntaje_contra', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('diferencia_puntaje', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('posicion', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencia.groupmodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competencia.tournamentmodel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.teammodel')),
            ],
            options={
                'db_table': 'competencia_standing',
            },
        ),
        migrations.CreateModel(
            name='ParticipantModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('grado_academico', models.CharField(max_length=50)),
                ('rol_en_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_identidad', models.CharField(max_length=50)),
                ('autorizacion_datos', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competencia.teammodel')),
            ],
            options={
                'db_table': 'competencia_participant',
            },
        ),
        migrations.CreateModel(
            name='MatchResultModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('valor_registrado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_normalizado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estado_resultado', models.CharField(max_length=50)),
                ('registrado_por', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.criteriamodel')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competencia.matchmodel')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.teammodel')),
            ],
            options={
                'db_table': 'competencia_match_result',
            },
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='equipo_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_local', to='competencia.teammodel'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='equipo_visitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_visitor', to='competencia.teammodel'),
        ),
        migrations.CreateModel(
            name='FinalRankingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_final', models.IntegerField()),
                ('puntaje_total_acumulado', models.DecimalField(decimal_places=4, max_digits=12)),
                ('medalla', models.CharField(blank=True, max_length=50, null=True)),
                ('mencion_especial', models.CharField(blank=True, max_length=200, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_ranking', to='competencia.tournamentmodel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencia.teammodel')),
            ],
            options={
                'db_table': 'competencia_final_ranking',
            },
        ),
    ]
