# Generated by Django 6.0.4 on 2026-04-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0004_criterioiamodel'),
        ('competencia', '0006_institutionmodel_groupmodel_docenteasesormodel_and_more'),
    ]

    operations = [
    ]
