# Generated by Django 6.0.4 on 2026-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0007_merge_20260430_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlpanalysismodel',
            name='fecha_fin_sugerida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nlpanalysismodel',
            name='fecha_inicio_sugerida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nlpanalysismodel',
            name='nombre_torneo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
