# Generated by Django 6.0.4 on 2026-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0008_nlpanalysismodel_fecha_fin_sugerida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlpanalysismodel',
            name='descripcion_sugerida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
