# Generated by Django 6.0.4 on 2026-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('attempts', models.IntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'authentication_user',
            },
        ),
    ]
