# Generated by Django 6.0.4 on 2026-04-30 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usermodel_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
