# Generated by Django 6.0.4 on 2026-05-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0003_simulacionresultado'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analisisentrega',
            new_name='simulacion__partici_6c2a4b_idx',
            old_name='sim_analisis_part_torn_idx',
        ),
        migrations.RenameIndex(
            model_name='analisisentrega',
            new_name='simulacion__reto_id_f297c4_idx',
            old_name='sim_analisis_reto_idx',
        ),
        migrations.RenameIndex(
            model_name='simulacionpredictiva',
            new_name='simulacion__partici_1bb598_idx',
            old_name='simulacion__partici_torneo_idx',
        ),
        migrations.RenameIndex(
            model_name='simulacionpredictiva',
            new_name='simulacion__creado__a0742a_idx',
            old_name='simulacion__creado__idx',
        ),
        migrations.RenameIndex(
            model_name='simulacionresultado',
            new_name='simulacion__tournam_b3b430_idx',
            old_name='sim_result_tourn_equipo_idx',
        ),
        migrations.RenameIndex(
            model_name='simulacionresultado',
            new_name='simulacion__creado__098333_idx',
            old_name='sim_result_creado_idx',
        ),
        migrations.AlterField(
            model_name='simulacionpredictiva',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
